"""Protocol definitions for femtologging configuration builders."""

from __future__ import annotations

import typing as typ


class _ConfigBuilder(typ.Protocol):
    """Protocol describing the builder interface used by ``dictConfig``."""

    def with_filter(self, fid: str, builder: object) -> typ.Self: ...

    def with_formatter(self, fid: str, builder: object) -> typ.Self: ...

    def with_handler(self, hid: str, builder: object) -> typ.Self: ...

    def with_logger(self, lname: str, builder: object) -> typ.Self: ...

    def with_root_logger(self, builder: object) -> typ.Self: ...

    def build_and_init(self) -> None: ...


class _LoggerMutationBuilder(typ.Protocol):
    """Protocol matching the concrete ``LoggerMutationBuilder`` API."""

    def with_level(self, level: object) -> typ.Self: ...

    def with_propagate(self, propagate: bool) -> typ.Self: ...  # noqa: FBT001  # TODO(#340): protocol mirrors the public builder API's boolean setter

    def replace_handlers(self, ids: list[str]) -> typ.Self: ...

    def append_handlers(self, ids: list[str]) -> typ.Self: ...

    def remove_handlers(self, ids: list[str]) -> typ.Self: ...

    def clear_handlers(self) -> typ.Self: ...

    def replace_filters(self, ids: list[str]) -> typ.Self: ...

    def append_filters(self, ids: list[str]) -> typ.Self: ...

    def remove_filters(self, ids: list[str]) -> typ.Self: ...

    def clear_filters(self) -> typ.Self: ...

    def as_dict(self) -> dict[str, object]: ...


class _RuntimeConfigBuilder(typ.Protocol):
    """Protocol describing the runtime mutation builder interface."""

    def with_filter(self, fid: str, builder: object) -> typ.Self: ...

    def with_handler(self, hid: str, builder: object) -> typ.Self: ...

    def with_logger(
        self,
        lname: str,
        builder: _LoggerMutationBuilder,
    ) -> typ.Self: ...

    def with_root_logger(self, builder: _LoggerMutationBuilder) -> typ.Self: ...

    def apply(self) -> None: ...

    def as_dict(self) -> dict[str, object]: ...
